main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^train/$', views.train, name='train'),
    url(r'^similar/$', views.get_similar, name='similar')
]

review2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models


class Article(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=100)
    summary = models.CharField(max_length=5000)

main/views.py
import os
from heapq import heappush, heappop
import pickle
import requests

from django.shortcuts import render
import wikipedia
from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse
import pandas as pd
import bs4

from main.models import Article


def index(request):
    if os.path.exists('model.pickle') and os.path.exists('data.npz'):
        return render(request, 'main/index.html')
    return render(request, 'main/need_train.html')


def train(request):
    max_articles_train = 20000

    Article.objects.all().delete()
    try:
        data = pd.read_csv('wiki_movie_plots_deduped.csv').sample(max_articles_train)
    except Exception as e:
        return render(request, 'main/error.html')
    text_corpus = list(data.Plot)

    articles = [Article(number=i, title=data.iloc[i].Title, url=data.iloc[i]['Wiki Page'], summary=data.iloc[i].Plot)
                for i in range(data.shape[0])]

    Article.objects.bulk_create(articles)

    model = TfidfVectorizer(analyzer='word', stop_words='english', strip_accents='ascii')
    param_matrix = model.fit_transform(text_corpus)

    if os.path.exists("model.pickle"):
        os.remove("model.pickle")

    if os.path.exists("data.npz"):
        os.remove("data.npz")

    with open('model.pickle', 'wb') as f:
        pickle.dump(model, f)
    scipy.sparse.save_npz('data.npz', param_matrix)

    return render(request, 'main/train.html')


def get_similar(request):
    try:
        url = request.GET['url']
        cnt = int(request.GET['cnt'])
        response = requests.get(url)
    except Exception as e:
        return render(request, 'main/error.html')
    if response:
        html = bs4.BeautifulSoup(response.text, 'html.parser')
        title = html.select("#firstHeading")[0].text
    else:
        context = {'url': url}
        return render(request, 'main/not_found.html', context)
    try:
        page = wikipedia.page(title)
        content = page.content
    except Exception as e:
        return render(request, 'main/error.html')
    if not os.path.exists('model.pickle') or not os.path.exists('data.npz'):
        return render(request, 'main/need_train.html')
    with open('model.pickle', 'rb') as model_file:
        model = pickle.load(model_file)
    data = scipy.sparse.load_npz('data.npz')
    film_summary_vector = model.transform([content]).toarray()
    row_number = 0
    top = []
    for row in data:
        vec = row.toarray()
        dist = scipy.spatial.distance.euclidean(vec, film_summary_vector)
        heappush(top, (-dist, row_number))
        if len(top) > cnt:
            heappop(top)
        row_number += 1

    top = sorted(top, reverse=True)
    films = []
    for dist, num in top:
        film = Article.objects.get(number=num)
        films.append(film)
    context = {'films': films, 'query_film': page.title}
    return render(request, 'main/get_similar.html', context)

main/templates/main/error.html
<h1>Invalid query!</h1>

main/templates/main/get_similar.html
<h1>Films, similar to {{query_film}}: </h1>
{% for film in films %}
    <h2><a href="{{film.url}}">{{film.title}}</a></h2>
    <p>
        {{film.summary}}
    </p>
    <hr>
{% endfor %}

main/templates/main/index.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>Type your wikipedia page address here:</h1>
<form action="{% url 'main:similar' %}" method="get">
    <input size="70" style= "height: 30px;" type="text" name="url" />
    <select style= "height: 30px; width: 70px;" name="cnt">
        <option selected value="5">5</option>
        <option value="10">10</option>
        <option value="15">15</option>
        <option value="20">20</option>
   </select>
</form>

main/templates/main/need_train.html
<h1>Model is not trained! You should <a href="/train/">train</a> it!</h1>

main/templates/main/not_found.html
<h1>Page <a href="{{url}}">{{url}}</a> not found!</h1>

main/templates/main/train.html
<h1>Model trained!</h1>